#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.1 on Sun Apr 25 12:38:05 2021
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((500, 600))
        self.SetTitle("frame")

        self.panel_1 = wx.Panel(self, wx.ID_ANY)

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        self.panel_2 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.panel_2.SetMinSize((498, 400))
        sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)

        grid_sizer_1 = wx.GridSizer(10, 3, 0, 0)

        self.button_1 = wx.Button(self.panel_2, wx.ID_ANY, "button_1")
        grid_sizer_1.Add(self.button_1, 0, wx.EXPAND, 0)

        self.text_ctrl_1 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_1, 0, wx.EXPAND, 0)

        label_1 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_1")
        grid_sizer_1.Add(label_1, 0, wx.EXPAND, 0)

        self.button_2 = wx.Button(self.panel_2, wx.ID_ANY, "button_2")
        grid_sizer_1.Add(self.button_2, 0, wx.EXPAND, 0)

        self.text_ctrl_2 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_2, 0, wx.EXPAND, 0)

        label_2 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_2")
        grid_sizer_1.Add(label_2, 0, wx.EXPAND, 0)

        self.button_3 = wx.Button(self.panel_2, wx.ID_ANY, "button_3")
        grid_sizer_1.Add(self.button_3, 0, wx.EXPAND, 0)

        self.text_ctrl_3 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_3, 0, wx.EXPAND, 0)

        label_3 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_3")
        grid_sizer_1.Add(label_3, 0, wx.EXPAND, 0)

        self.button_4 = wx.Button(self.panel_2, wx.ID_ANY, "button_4")
        grid_sizer_1.Add(self.button_4, 0, wx.EXPAND, 0)

        self.text_ctrl_4 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_4, 0, wx.EXPAND, 0)

        label_4 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_4")
        grid_sizer_1.Add(label_4, 0, wx.EXPAND, 0)

        self.button_5 = wx.Button(self.panel_2, wx.ID_ANY, "button_5")
        grid_sizer_1.Add(self.button_5, 0, wx.EXPAND, 0)

        self.text_ctrl_5 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_5, 0, wx.EXPAND, 0)

        label_5 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_5")
        grid_sizer_1.Add(label_5, 0, wx.EXPAND, 0)

        self.button_6 = wx.Button(self.panel_2, wx.ID_ANY, "button_6")
        grid_sizer_1.Add(self.button_6, 0, wx.EXPAND, 0)

        self.text_ctrl_6 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_6, 0, wx.EXPAND, 0)

        label_6 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_6")
        grid_sizer_1.Add(label_6, 0, wx.EXPAND, 0)

        self.button_7 = wx.Button(self.panel_2, wx.ID_ANY, "button_7")
        grid_sizer_1.Add(self.button_7, 0, wx.EXPAND, 0)

        self.text_ctrl_7 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_7, 0, wx.EXPAND, 0)

        label_7 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_7")
        grid_sizer_1.Add(label_7, 0, wx.EXPAND, 0)

        self.button_8 = wx.Button(self.panel_2, wx.ID_ANY, "button_8")
        grid_sizer_1.Add(self.button_8, 0, wx.EXPAND, 0)

        self.text_ctrl_8 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_8, 0, wx.EXPAND, 0)

        label_8 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_8")
        grid_sizer_1.Add(label_8, 0, wx.EXPAND, 0)

        self.button_9 = wx.Button(self.panel_2, wx.ID_ANY, "button_9")
        grid_sizer_1.Add(self.button_9, 0, wx.EXPAND, 0)

        self.text_ctrl_9 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_9, 0, wx.EXPAND, 0)

        label_9 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_9")
        grid_sizer_1.Add(label_9, 0, wx.EXPAND, 0)

        self.button_10 = wx.Button(self.panel_2, wx.ID_ANY, "button_10")
        grid_sizer_1.Add(self.button_10, 0, wx.EXPAND, 0)

        self.text_ctrl_10 = wx.TextCtrl(self.panel_2, wx.ID_ANY, "")
        grid_sizer_1.Add(self.text_ctrl_10, 0, wx.EXPAND, 0)

        label_10 = wx.StaticText(self.panel_2, wx.ID_ANY, "output_10")
        grid_sizer_1.Add(label_10, 0, wx.EXPAND, 0)

        self.text_ctrl_logging = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        sizer_1.Add(self.text_ctrl_logging, 1, wx.EXPAND, 0)

        self.panel_2.SetSizer(grid_sizer_1)

        self.panel_1.SetSizer(sizer_1)

        self.Layout()
        # end wxGlade

# end of class MyFrame

class MyApp(wx.App):
    def OnInit(self):
        self.frame = MyFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.frame)
        self.frame.Show()
        return True

# end of class MyApp

if __name__ == "__main__":
    app = MyApp(0)
    app.MainLoop()
